### ISSUE TITLE
Doesn't work properly on 1.20.1

### ISSUE THREAD

**Issue by BingYanchi** [Doclic/NoEncryption#120]
### Are you using the latest version of NoEncryption?

- [X] I am using the latest version of NoEncryption compatible with my server version.

### Is there an existing issue for this?

- [x] I have searched the existing issues and have not found a duplicate relating to my issue.

### NoEncryption Version

5.2

### Minecraft Version

1.20.1

### Server Type/Build

CraftBukkit version 3811-Spigot-c62f4bd-85b89c3 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugins in Use

NoEncryption

### Startup/Running Logs

```c
[16:35:06] [Server thread/INFO]: [NoEncryption] Enabling NoEncryption v5.2
[16:35:06] [Server thread/INFO]: [NoEncryption] Your server is running version 1.20.1
[16:35:06] [Server thread/INFO]: [NoEncryption] Checking for new config option...
[16:35:06] [Server thread/INFO]: [NoEncryption] No new config options detected
[16:35:06] [Server thread/INFO]: [NoEncryption] Checking for important messages...
[16:35:06] [Server thread/WARN]: [NoEncryption]   forward_uuid: "Due to Minecraft's new message validation techniques, this option is no longer supported in 1.19.3+"
[16:35:06] [Server thread/INFO]: [NoEncryption] These messages can be suppressed with /ne suppressnotices
[16:35:06] [Server thread/INFO]: [NoEncryption] Compatibility successful!
[16:35:06] [Server thread/INFO]: [NoEncryption] If you used /reload to update NoEncryption, your players need to disconnect and join back
[16:35:06] [Server thread/INFO]: [NoEncryption] bStats is enabled for NoEncryption by default. To disable this, or to see more info, check the NoEncryption config
[16:35:06] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:35:06] [Server thread/INFO]: Done (7.269s)! For help, type "help"
[16:35:08] [User Authenticator #1/INFO]: UUID of player Bing_Yanchi is 186dfa0d-8e66-4302-80a9-110bd79464b5
[16:35:09] [Server thread/ERROR]: [NoEncryption] Couldn't find field org.apache.logging.slf4j.Log4jLogger#b
[16:35:09] [Server thread/ERROR]: [NoEncryption] Please create an issue at
[16:35:09] [Server thread/ERROR]: [NoEncryption] https://github.com/Doclic/NoEncryption/issues
[16:35:09] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to NoEncryption v5.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:308) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:183) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.d(LoginListener.java:169) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:75) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:285) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:175) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: b
        at me.doclic.noencryption.compatibility.NMSInterface.getField(NMSInterface.java:38) ~[?:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getNetworkManager(NMSInterface.java:105) ~[?:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getNettyChannel(NMSInterface.java:115) ~[?:?]
        at me.doclic.noencryption.compatibility.versionhandler.VersionHandler.listen(VersionHandler.java:21) ~[?:?]
        at me.doclic.noencryption.PlayerListener.onPlayerJoin(PlayerListener.java:16) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
Caused by: java.lang.NoSuchFieldException: b
        at java.lang.Class.getField(Class.java:2117) ~[?:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getField(NMSInterface.java:30) ~[?:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getNetworkManager(NMSInterface.java:105) ~[?:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getNettyChannel(NMSInterface.java:115) ~[?:?]
        at me.doclic.noencryption.compatibility.versionhandler.VersionHandler.listen(VersionHandler.java:21) ~[?:?]
        at me.doclic.noencryption.PlayerListener.onPlayerJoin(PlayerListener.java:16) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
[16:35:09] [Server thread/INFO]: Bing_Yanchi joined the game
[16:35:09] [Server thread/INFO]: Bing_Yanchi[/127.0.0.1:3458] logged in with entity id 177 at ([world]78.4463944257827, 42.0, 262.37958070521665)
[16:35:14] [Server thread/INFO]: [NoEncryption] Your NoEncryption version is up-to-date
>version
[16:35:58] [Server thread/INFO]: This server is running CraftBukkit version 3811-Spigot-c62f4bd-85b89c3 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
[16:35:58] [Server thread/INFO]: Checking version, please wait...
[16:36:07] [Thread-10/INFO]: You are running the latest version
```

### Reproducible Test

1. run server
2. let player join server

### Anything else?

The PlayerJoinEvent reports an error when a player joins, and the signature information cannot be removed.

**Comment by BingYanchi** [comment]
The above error is generated when using `NoEncryption-Reflection-5.2.jar`.

Using `NoEncryption-1.20.1-5.2.jar` still has problems, but the error is different, as follows:
```c
[16:40:04] [Server thread/INFO]: [NoEncryption] Enabling NoEncryption v5.2
[16:40:04] [Server thread/INFO]: [NoEncryption] Your server is running version 1.20.1-R0.1-SNAPSHOT
[16:40:04] [Server thread/INFO]: [NoEncryption] Checking for new config option...
[16:40:04] [Server thread/INFO]: [NoEncryption] No new config options detected
[16:40:04] [Server thread/INFO]: [NoEncryption] Checking for important messages...
[16:40:04] [Server thread/WARN]: [NoEncryption]   forward_uuid: "Due to Minecraft's new message validation techniques, this option is no longer supported"
[16:40:04] [Server thread/INFO]: [NoEncryption] These messages can be suppressed with /ne suppressnotices
[16:40:04] [Server thread/INFO]: [NoEncryption] Compatibility successful!
[16:40:04] [Server thread/INFO]: [NoEncryption] If you used /reload to update NoEncryption, your players need to disconnect and join back
[16:40:04] [Server thread/INFO]: [NoEncryption] bStats is enabled for NoEncryption by default. To disable this, or to see more info, check the NoEncryption config
[16:40:04] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:40:04] [Server thread/INFO]: Done (7.522s)! For help, type "help"
[16:40:06] [User Authenticator #1/INFO]: UUID of player Bing_Yanchi is 186dfa0d-8e66-4302-80a9-110bd79464b5
[16:40:07] [Server thread/ERROR]: [NoEncryption] An error occurred while retrieving the player's channel for injection!
[16:40:07] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to NoEncryption v5.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:308) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:183) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.d(LoginListener.java:169) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:75) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:285) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:175) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3811-Spigot-c62f4bd-85b89c3]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: class me.doclic.noencryption.compatibility.CompatiblePlayer cannot access a member of class net.minecraft.server.network.PlayerConnection with modifiers "private final"
        at me.doclic.noencryption.PlayerListener.onPlayerJoin(PlayerListener.java:22) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
Caused by: java.lang.IllegalAccessException: class me.doclic.noencryption.compatibility.CompatiblePlayer cannot access a member of class net.minecraft.server.network.PlayerConnection with modifiers "private final"
        at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
        at java.lang.reflect.Field.checkAccess(Field.java:1102) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:423) ~[?:?]
        at me.doclic.noencryption.compatibility.CompatiblePlayer.getChannel(CompatiblePlayer.java:29) ~[?:?]
        at me.doclic.noencryption.PlayerListener.onPlayerJoin(PlayerListener.java:19) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 15 more
[16:40:07] [Server thread/INFO]: Bing_Yanchi joined the game
[16:40:07] [Server thread/INFO]: Bing_Yanchi[/127.0.0.1:4478] logged in with entity id 178 at ([world]78.30000001192093, 42.0, 262.4486195820858)
[16:40:12] [Server thread/INFO]: [NoEncryption] Your NoEncryption version is up-to-date
```

**Comment by whytf** [comment]
can confirm

**Comment by gamergeek1213** [comment]
I can also confirm

**Comment by sleoj** [comment]
can confirm here too

**Comment by Stoupy51** [comment]
Also confirm

**Comment by Rosaaalfi** [comment]
i have this issue from my server

**Comment by SoloPlayer88** [comment]
Confirmed. running 1.20.1
