### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by lerokko** [Doclic/NoEncryption#130]
### Is there an existing question issue for this?

- [X] I have searched the existing issues and have not found a duplicate relating to my issue.

### Subject of Issue

Please add 1.20.2 support to the plugin.

### Details

And preferably 1.20.3 when that drops in the next weeks.

**Comment by editon96** [comment]
I need it also.

**Comment by editon96** [comment]
Here the Error if I use the Reflexion version under 1.20.2:

```
[16:18:54 ERROR]: [NoEncryption] Couldn't find field org.apache.logging.slf4j.Log4jLogger#b
[16:18:54 ERROR]: [NoEncryption] Please create an issue at
[16:18:54 ERROR]: [NoEncryption] https://github.com/Doclic/NoEncryption/issues
[16:18:54 ERROR]: Could not pass event PlayerJoinEvent to NoEncryption v5.2
java.lang.RuntimeException: java.lang.NoSuchFieldException: b
        at me.doclic.noencryption.compatibility.NMSInterface.getField(NMSInterface.java:38) ~[NoEncryption-Reflection-5.2.jar:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getNetworkManager(NMSInterface.java:105) ~[NoEncryption-Reflection-5.2.jar:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getNettyChannel(NMSInterface.java:115) ~[NoEncryption-Reflection-5.2.jar:?]
        at me.doclic.noencryption.compatibility.versionhandler.VersionHandler.listen(VersionHandler.java:21) ~[NoEncryption-Reflection-5.2.jar:?]
        at me.doclic.noencryption.PlayerListener.onPlayerJoin(PlayerListener.java:16) ~[NoEncryption-Reflection-5.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor890.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:346) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchFieldException: b
        at java.lang.Class.getField(Class.java:2117) ~[?:?]
        at me.doclic.noencryption.compatibility.NMSInterface.getField(NMSInterface.java:30) ~[NoEncryption-Reflection-5.2.jar:?]
        ... 29 more
```

**Comment by editon96** [comment]
Maybe @lerokko you can add the Error from the 1.20.1 from Releses.
