### ISSUE TITLE
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component

### ISSUE THREAD

**Issue by zhro** [Doclic/NoEncryption#30]
```
2022-09-25 07:17:58 [INFO] [NoEncryption] Enabling NoEncryption v3.1
2022-09-25 07:17:58 [INFO] Your server is running version 1.19.2-R0.1-SNAPSHOT
2022-09-25 07:17:58 [INFO] [NoEncryption] Checking for new config option...
2022-09-25 07:17:58 [INFO] [NoEncryption] No new config options detected
2022-09-25 07:17:58 [INFO] [NoEncryption] Checking for important messages...
2022-09-25 07:17:58 [INFO] [NoEncryption] No important messages detected
2022-09-25 07:17:58 [ERROR] Error occurred while enabling NoEncryption v3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at me.doclic.noencryption.NoEncryption.onEnable(NoEncryption.java:27) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:523) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:437) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
```

I get this error while trying to load this with Spigot 1.19.2. Is there a dependency missing?

**Comment by V1nc3ntWasTaken** [comment]
Prime example of what happens when Bukkit switches over to using a different chat component system, and why they should have went more gradually. I'll look at this later on tonight.

**Comment by V1nc3ntWasTaken** [comment]
Can you send me your `/ver`/`/about`?

**Comment by Doclic** [comment]
@V1nc3ntWasTaken I believe regular Spigot doesn't use the adventure API. I know PaperSpigot uses it though

**Comment by kralverde** [comment]
im getting this error with `/ver` `This server is running CraftBukkit version 3594-Spigot-4aa5ead-9306170 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)` as well
